
-- GRANT ALL PRIVILEGES ON SCHEMA pgmq TO dbuser;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA pgmq TO dbuser;
GRANT USAGE ON SCHEMA pgmq TO dbuser;
GRANT CREATE ON SCHEMA pgmq TO dbuser;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgmq TO dbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA pgmq GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO dbuser;

