
GRANT USAGE ON SCHEMA pgmq TO dbuser;
-- GRANT SELECT ON ALL TABLES IN SCHEMA pgmq TO dbuser;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA pgmq GRANT SELECT ON TABLES TO dbuser;
-- GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA pgmq TO dbuser;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA pgmq GRANT INSERT, UPDATE, DELETE ON TABLES TO dbuser;
-- GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA pgmq TO dbuser;
GRANT ALL PRIVILEGES ON SCHEMA pgmq TO dbuser;

