
CREATE USER dbuser WITH PASSWORD 'dbuser';
GRANT USAGE ON SCHEMA public TO dbuser;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dbuser;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO dbuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, UPDATE, DELETE ON TABLES TO dbuser;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO dbuser;
\du+;

