
CREATE USER $DBUSER WITH PASSWORD '$DBUSER_PWD';
GRANT USAGE ON SCHEMA public TO $DBUSER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DBUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO $DBUSER;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $DBUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT, UPDATE, DELETE ON TABLES TO $DBUSER;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DBUSER;
\du+;

